export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  LOGIN: '/signin',
  SIGNUP: '/signup',
  OTP_VERIFICATION: '/verify-email',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/product/:id',
  CREATE_PRODUCT: '/create-product',
  EDIT_PRODUCT: '/edit-product',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_SUCCESS: '/confirmation/:orderId',
  ORDER_FAILED: '/order-failed',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  STAFF_ACCEPTION_INVITATION: '/staff/accept-invitation',
  PROFILE: '/profile',
  CUSTOMER_ORDER: '/orders',
  CUSTOMER_ORDER_DETAIL: '/order/:id',
  CUSTOMER_PAYMENT_DETAIL: '/payment/:id',

  NOT_FOUND: '*',
  // ORDER_FAILED: "/order-failed",
  // FORGOT_PASSWORD: "/forgot-password",
};
