import {
  LayoutDashboard,
  BarChart2,
  Package,
  Store,
  ClipboardList,
  Receipt,
  TerminalSquare,
  Settings,
  ShoppingBag,
  CreditCard,
  HelpCircle,
  Search,
} from 'lucide-react';

// Define tab structure with clean labels, grouping sections, and channel requirements
export const ALL_TABS = [
  // --- General ---
  {
    name: 'dashboard.overview',
    label: 'Overview',
    icon: LayoutDashboard,
    path: 'overview',
    roles: ['admin', 'user'],
    permission: null,
    section: 'general',
  },
  {
    name: 'dashboard.analytics',
    label: 'Analytics',
    icon: BarChart2,
    path: 'analytics',
    roles: ['admin', 'user'],
    permission: null,
    section: 'general',
  },

  // --- Operations ---
  {
    name: 'dashboard.product.title',
    label: 'Products',
    icon: Package,
    path: 'products',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_products',
    section: 'operations',
  },
  {
    name: 'dashboard.product.detail',
    label: 'Product Detail',
    icon: Package,
    path: 'products/:id',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_products',
    hideInSidebar: true,
  },
  {
    name: 'create product',
    label: 'Create Product',
    icon: Package,
    path: 'products/create',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_products',
    hideInSidebar: true,
  },
  {
    name: 'Store catalog',
    label: 'Store Catalog',
    icon: Package,
    path: 'catalog',
    roles: ['admin', 'user'],
    permission: null,
    channel: 'storefront',
    hideInSidebar: true,
  },
  {
    name: 'dashboard.order.title',
    label: 'Orders',
    icon: ClipboardList,
    path: 'orders',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_orders',
    section: 'operations',
  },
  {
    name: 'dashboard.order.detail',
    label: 'Order Detail',
    icon: ClipboardList,
    path: 'orders/:id',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_orders',
    hideInSidebar: true,
  },
  {
    name: 'dashboard.invoices.title',
    label: 'Invoices',
    icon: Receipt,
    path: 'invoices',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_invoices',
    section: 'operations',
  },
  {
    name: 'dashboard.pos.title',
    label: 'Point of Sale',
    icon: TerminalSquare,
    path: 'pos',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_pos',
    channel: 'pos',
    section: 'operations',
  },

  // --- Channels ---
  {
    name: 'dashboard.store_management.title',
    label: 'Storefront Website',
    icon: Store,
    path: 'store-management',
    roles: ['admin', 'user'],
    permission: null,
    features: ['store'],
    channel: 'storefront',
    section: 'channels',
  },
  {
    name: 'COD orders',
    label: 'Marketplace Orders',
    icon: ShoppingBag,
    path: 'marketplace-orders',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_orders',
    channel: 'marketplace',
    section: 'channels',
  },

  // --- System ---
  {
    name: 'dashboard.settings.title',
    label: 'Settings',
    icon: Settings,
    path: 'settings',
    roles: ['admin', 'user', 'staff'],
    permission: 'settings',
    section: 'system',
    hasSubmenu: true,
    subItems: [
      { name: 'Account', path: 'settings/account' },
      { name: 'Preferences', path: 'settings/preferences' },
      { name: 'Security', path: 'settings/security' },
      { name: 'Payments', path: 'settings/payments' },
      { name: 'Staff', path: 'settings/staff' },
      { name: 'Billing', path: 'settings/billing' },
    ],
  },
  {
    name: 'dashboard.usage.title',
    label: 'Usage & Billing',
    icon: CreditCard,
    path: 'usage',
    roles: ['admin', 'user', 'staff'],
    permission: 'manage_analytics',
    section: 'system',
    hasSubmenu: true,
    subItems: [
      { name: 'Dashboard', path: 'usage/dashboard' },
      { name: 'Breakdown', path: 'usage/breakdown' },
      { name: 'Billing', path: 'usage/billing' },
    ],
  },
];

export const ADDITIONAL_NAV_ITEMS = {
  documents: [],
  secondary: [
    {
      name: 'Get Help',
      icon: HelpCircle,
      path: 'help',
    },
    {
      name: 'Search',
      icon: Search,
      path: 'search',
    },
  ],
};
