declare const __API_URL__: string;
declare const __ECOMMERCE_API_: string;
declare const __AUTH__URL__: string;
declare const __DASHBOARD__URL__: string;
declare const __MARKETING_URL__: string;
declare const __MARKETPLACE_URL__: string;
declare const __STOREFRONT_ORIGIN__: string;
declare const __HOSTED_STOREFRONT_DOMAIN__: string;
declare const __HOSTED_STOREFRONT_BUYER_ENABLED__: boolean;
