// Owner-tool copy in English and Khmer. Follows the language the template set
// on <html lang>, so it switches with the store's language toggle.
const SECTIONS = {
  en: {
    Header: 'Announcement bar',
    Hero: 'Hero',
    homepage: 'Hero',
    Highlights: 'Highlights',
    'Feature Banner': 'Feature banner',
    'Featured Products': 'Featured row',
    'Shop by Need': 'Shop by need',
    'Our Story': 'Our story',
  },
  km: {
    Header: 'របារប្រកាស',
    Hero: 'ផ្ទាំងដើម',
    homepage: 'ផ្ទាំងដើម',
    Highlights: 'ចំណុចលេចធ្លោ',
    'Feature Banner': 'ផ្ទាំងពិសេស',
    'Featured Products': 'ជួរទំនិញពិសេស',
    'Shop by Need': 'ទិញតាមតម្រូវការ',
    'Our Story': 'រឿងរ៉ាវរបស់យើង',
  },
};

const TEXT = {
  en: {
    edit: 'Edit',
    addProduct: 'Add product',
    addCategory: 'Add category',
    newProduct: 'New product',
    newCategory: 'New category',
    productHelp: 'Appears in your store and the marketplace as soon as you add it.',
    categoryHelp: 'Group your products so shoppers can browse them.',
    name: 'Name',
    price: 'Price (USD)',
    stock: 'Stock quantity',
    category: 'Category',
    noCategory: 'No category',
    description: 'Description',
    photos: 'Photos',
    photo: 'Photo',
    adding: 'Adding…',
    added: 'Added to your store.',
    viewProduct: 'View product',
    addAnother: 'Add another',
    required: 'Required',
    pricePositive: 'Enter a price above 0',
    addFailed: 'Could not add it. Please check the details and try again.',
    loadingForm: 'Loading…',
    yourStore: 'Your store',
    editStore: 'Edit store',
    dashboard: 'Dashboard',
    title: 'Edit your store',
    subtitle: 'Changes appear for shoppers as soon as you save.',
    close: 'Close',
    save: 'Save changes',
    saving: 'Saving…',
    saved: 'Saved. Your store is updated.',
    saveFailed: 'Could not save. Check the highlighted fields and try again.',
    noChanges: 'No changes yet',
    upload: 'Upload image',
    uploading: 'Uploading…',
    uploadFailed: 'That image could not be uploaded. Use a JPG, PNG or WebP under 5 MB.',
    remove: 'Remove',
    removeImage: 'Remove image',
    onlyYouSeeThis: 'Only you can see this. It stays hidden from shoppers until you fill it in.',
    addSection: (section) => `Add ${sectionName('en', section).toLowerCase()}`,
  },
  km: {
    edit: 'កែ',
    addProduct: 'បន្ថែមទំនិញ',
    addCategory: 'បន្ថែមប្រភេទ',
    newProduct: 'ទំនិញថ្មី',
    newCategory: 'ប្រភេទថ្មី',
    productHelp: 'បង្ហាញក្នុងហាង និងទីផ្សាររបស់អ្នកភ្លាមៗ ពេលអ្នកបន្ថែម។',
    categoryHelp: 'ដាក់ទំនិញជាក្រុម ដើម្បីឲ្យអតិថិជនងាយរកមើល។',
    name: 'ឈ្មោះ',
    price: 'តម្លៃ (USD)',
    stock: 'ចំនួនក្នុងស្តុក',
    category: 'ប្រភេទ',
    noCategory: 'គ្មានប្រភេទ',
    description: 'ការពិពណ៌នា',
    photos: 'រូបភាព',
    photo: 'រូបភាព',
    adding: 'កំពុងបន្ថែម…',
    added: 'បានបន្ថែមទៅហាងរបស់អ្នក។',
    viewProduct: 'មើលទំនិញ',
    addAnother: 'បន្ថែមមួយទៀត',
    required: 'ត្រូវបំពេញ',
    pricePositive: 'សូមបញ្ចូលតម្លៃធំជាង 0',
    addFailed: 'មិនអាចបន្ថែមបានទេ។ សូមពិនិត្យព័ត៌មាន ហើយព្យាយាមម្តងទៀត។',
    loadingForm: 'កំពុងផ្ទុក…',
    yourStore: 'ហាងរបស់អ្នក',
    editStore: 'កែហាង',
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    title: 'កែហាងរបស់អ្នក',
    subtitle: 'អតិថិជននឹងឃើញការផ្លាស់ប្តូរភ្លាមៗ ពេលអ្នករក្សាទុក។',
    close: 'បិទ',
    save: 'រក្សាទុក',
    saving: 'កំពុងរក្សាទុក…',
    saved: 'បានរក្សាទុក។ ហាងរបស់អ្នកត្រូវបានធ្វើបច្ចុប្បន្នភាព។',
    saveFailed: 'មិនអាចរក្សាទុកបានទេ។ សូមពិនិត្យវាលដែលបានសម្គាល់ ហើយព្យាយាមម្តងទៀត។',
    noChanges: 'មិនទាន់មានការផ្លាស់ប្តូរ',
    upload: 'បង្ហោះរូបភាព',
    uploading: 'កំពុងបង្ហោះ…',
    uploadFailed: 'មិនអាចបង្ហោះរូបភាពនេះបានទេ។ សូមប្រើ JPG, PNG ឬ WebP តូចជាង 5 MB។',
    remove: 'លុប',
    removeImage: 'លុបរូបភាព',
    onlyYouSeeThis: 'មានតែអ្នកទេដែលឃើញផ្នែកនេះ។ អតិថិជនមិនឃើញទេ រហូតដល់អ្នកបំពេញវា។',
    addSection: (section) => `បន្ថែម${sectionName('km', section)}`,
  },
};

const sectionName = (language, section) => SECTIONS[language][section] || section || '';

export const ownerText = () => {
  const language = typeof document !== 'undefined' && document.documentElement.lang === 'km' ? 'km' : 'en';
  return { ...TEXT[language], sectionName: (section) => sectionName(language, section) };
};
